# -*- coding: utf-8 -*-
"""
Created on Wed Aug  6 14:24:59 2025

@author: Georg
"""

# DATABASE AND DB FILE
SCHEMA = 'texas_schools'
DB_FILE = 'texas_schools.db'

CLEANED_DB_FILE = ''
DISTRICTS_DATA_FILE = 'DM/district-types.csv'
COUNTIES_DATA_FILE = 'DM/texas-county-data.csv'


# Tables names from database
AVERAGES = 'average_sat_scores'
GROUPS = 'group_categories'
DISTRICTS = 'districts'
REGIONS = 'regions'
COUNTIES = 'counties'
PERFORMANCE_SCORES = 'all_sat_scores_cleaned'

# Added 
ALL_STUDENTS = 'sat_scores_all_students'
DF_BY_GROUP = 'sat_scores_by_group'
DF_DISTRICTS_CLEANED = 'districts_cleaned'
DF_COUNTIES_CLEANED = 'counties_cleaned'

# COLUMNS
SCORE_ID = 'SCORE_ID'
CLASS = 'CLASS'
GROUP_NUM = 'GROUP_NUM'
DISTRICT_NUM = 'DISTRICT_NUMBER'
COUNTY = 'COUNTY_NUMBER'
REGION_NUM = 'REGION_NUMBER'
MATH_SCORE = 'MATH'
CRIT_READING_SCORE = 'CRITRD'
WRITING_SCORE = 'WRITING'
READING_WRITING_SCORE = 'ERW'
TOTAL_SCORE = 'TOTAL'
ABOVE_CRIT_RATE = 'ABOVE_CRIT_RATE'
EXAMINEES = 'EXNEES_MSKD'
CRITERION = 'CRIT_MSKD'
PARTICIPATION_RATE = 'PART_RATE'
GRADUATES = 'GRADS_MSKD'
TSI = 'TSI_BOTH_MSKD'
TSI_RATE = 'ABOVE_TSI_BOTH_RATE'
QUARTILE = 'QUARTILE'
RUNNING_SCORE = 'SCORE'
GROUP_NAME = 'GROUP_NAME'
PERFORMANCE = 'PERFORMANCE'
CLM_DTYPES_DISTRICT_NAME = 'DISTRICT_NAME'
CLM_REGIONS_REGION_NAME = 'REGION_NAME'

#District-Types
CLM_DTYPES_DISTRICT_NUMBER = 'DISTRICT_NUMBER'
CLM_DTYPES_TYPE = 'DISTRICT_TYPE'
CLM_DTYPES_CHARTER = 'CHARTER'

#County Info
CLM_COUNTIES_COUNTY_NAME = 'COUNTY_NAME'
CLM_COUNTIES_BUSINESSES = 'COUNTY_ESTABLISHMENTS'
CLM_COUNTIES_EMPLOYMENT = 'COUNTY_EMPLOYMENT'
CLM_COUNTIES_WAGE = 'COUNTY_WEEKLY_WAGE'

# Added county info
CLM_COUNTIES_ECONOMIC_DENSITY = 'ECONOMIC_DENSITY'
CLM_COUNTIES_REL_WEEKLY_SAL = 'RELATIVE_WEEKLY_SALARY'
CLM_COUNTIES_ACTIVITY_INDEX = 'ECONOMIC_ACTIVITY_INDEX'

#OTHER CONSTANTS
MAX_SAT_SCORE = 1600
MIN_SAT_SCORE = 400